/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagTestenIndexRouteImport } from './routes/tag-testen/index'
import { Route as ResultatIndexRouteImport } from './routes/resultat/index'
import { Route as PartiernesStemmerIndexRouteImport } from './routes/partiernes-stemmer/index'
import { Route as OmTestenIndexRouteImport } from './routes/om-testen/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTestenIndexRoute = TagTestenIndexRouteImport.update({
  id: '/tag-testen/',
  path: '/tag-testen/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatIndexRoute = ResultatIndexRouteImport.update({
  id: '/resultat/',
  path: '/resultat/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiernesStemmerIndexRoute = PartiernesStemmerIndexRouteImport.update({
  id: '/partiernes-stemmer/',
  path: '/partiernes-stemmer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OmTestenIndexRoute = OmTestenIndexRouteImport.update({
  id: '/om-testen/',
  path: '/om-testen/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/om-testen/': typeof OmTestenIndexRoute
  '/partiernes-stemmer/': typeof PartiernesStemmerIndexRoute
  '/resultat/': typeof ResultatIndexRoute
  '/tag-testen/': typeof TagTestenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/om-testen': typeof OmTestenIndexRoute
  '/partiernes-stemmer': typeof PartiernesStemmerIndexRoute
  '/resultat': typeof ResultatIndexRoute
  '/tag-testen': typeof TagTestenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/om-testen/': typeof OmTestenIndexRoute
  '/partiernes-stemmer/': typeof PartiernesStemmerIndexRoute
  '/resultat/': typeof ResultatIndexRoute
  '/tag-testen/': typeof TagTestenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/om-testen/'
    | '/partiernes-stemmer/'
    | '/resultat/'
    | '/tag-testen/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/om-testen' | '/partiernes-stemmer' | '/resultat' | '/tag-testen'
  id:
    | '__root__'
    | '/'
    | '/om-testen/'
    | '/partiernes-stemmer/'
    | '/resultat/'
    | '/tag-testen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OmTestenIndexRoute: typeof OmTestenIndexRoute
  PartiernesStemmerIndexRoute: typeof PartiernesStemmerIndexRoute
  ResultatIndexRoute: typeof ResultatIndexRoute
  TagTestenIndexRoute: typeof TagTestenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag-testen/': {
      id: '/tag-testen/'
      path: '/tag-testen'
      fullPath: '/tag-testen/'
      preLoaderRoute: typeof TagTestenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultat/': {
      id: '/resultat/'
      path: '/resultat'
      fullPath: '/resultat/'
      preLoaderRoute: typeof ResultatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partiernes-stemmer/': {
      id: '/partiernes-stemmer/'
      path: '/partiernes-stemmer'
      fullPath: '/partiernes-stemmer/'
      preLoaderRoute: typeof PartiernesStemmerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-testen/': {
      id: '/om-testen/'
      path: '/om-testen'
      fullPath: '/om-testen/'
      preLoaderRoute: typeof OmTestenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OmTestenIndexRoute: OmTestenIndexRoute,
  PartiernesStemmerIndexRoute: PartiernesStemmerIndexRoute,
  ResultatIndexRoute: ResultatIndexRoute,
  TagTestenIndexRoute: TagTestenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
