services:
  web:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./server:/app
    working_dir: /app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
    command: sh -c "dotnet watch run --project ./Hvadskaljegstemme"

  db:
    image: postgres:18.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hvadskaljegstemme
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - db_data:/var/lib/postgresql/18/docker

  client:
    image: node:24.13
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    working_dir: /app
    networks:
      - default
    command: npm run dev

volumes:
  db_data:

networks:
  default:
    driver: bridge