export const mockBills = [
  {
    "id": 1,
    "bill_tag": "L 42",
    "title": "Forslag til lov om ændring af skatteloven",
    "question": "Skal der indføres en ny grøn afgift på dieselbiler?",
    "description": "Dette lovforslag vedrører indførelse af en progressiv afgift på dieselbiler for at fremme grøn omstilling og reducere CO2-udledning fra transportsektoren.",
    "for_description": "En grøn afgift vil accelerere overgangen til elbiler, reducere luftforurening i byerne og hjælpe Danmark med at nå klimamålene for 2030.",
    "against_description": "Afgiften vil ramme håndværkere og landdistrikter uforholdsmæssigt hårdt, hvor dieselbiler er nødvendige, og vil udgøre en økonomisk byrde for almindelige familier.",
    "url": "https://www.ft.dk/forslag/L42",
    "vote_date": "2024-03-15",
    "is_passed": true
  },
  {
    "id": 2,
    "bill_tag": "L 67",
    "title": "Forslag til lov om ændring af sundhedsloven",
    "question": "Skal der tilføjes flere midler til psykiatrien?",
    "description": "Lovforslaget foreslår en øget bevilling på 2 milliarder kroner til psykiatrien over de næste fire år med fokus på børne- og ungdomspsykiatrien.",
    "for_description": "Ventetiderne i psykiatrien er uacceptabelt lange. Flere midler vil redde liv, reducere ventelister og give bedre behandling til sårbare børn og unge.",
    "against_description": "Pengene kunne bruges mere effektivt andre steder i sundhedsvæsenet. Problemet er ikke manglende midler, men ineffektiv organisering og ressourcefordeling.",
    "url": "https://www.ft.dk/forslag/L67",
    "vote_date": "2024-04-22",
    "is_passed": true
  },
  {
    "id": 3,
    "bill_tag": "L 89",
    "title": "Forslag til lov om ændring af udlændingeloven",
    "question": "Skal asylbehandling flyttes til et land uden for EU?",
    "description": "Dette forslag indebærer etablering af asylcentre i et tredjeland, hvor asylansøgere skal behandles, mens de afventer afgørelse på deres ansøgning.",
    "for_description": "Eksterritorial asylbehandling vil reducere asyltilstrømningen, bekæmpe menneskesmugling og give Danmark bedre kontrol over, hvem der får opholdstilladelse.",
    "against_description": "Forslaget bryder med internationale konventioner, er dyrt at implementere og rejser alvorlige menneskelige og juridiske bekymringer om behandlingen af asylansøgere.",
    "url": "https://www.ft.dk/forslag/L89",
    "vote_date": "2024-05-10",
    "is_passed": false
  },
  {
    "id": 4,
    "bill_tag": "L 103",
    "title": "Forslag til lov om ændring af folkeskoleloven",
    "question": "Skal der indføres obligatorisk lektiehjælp i folkeskolen?",
    "description": "Lovforslaget forpligter alle folkeskoler til at tilbyde gratis lektiehjælp minimum tre gange om ugen efter skoletid for alle elever fra 1. til 9. klasse.",
    "for_description": "Obligatorisk lektiehjælp vil mindske den sociale ulighed i uddannelsessystemet og give alle børn samme muligheder uanset forældrenes ressourcer.",
    "against_description": "Forslaget er en unødvendig statslig indblanding i familiernes hverdag og vil koste kommunerne store summer, som bedre kunne bruges på undervisningskvalitet.",
    "url": "https://www.ft.dk/forslag/L103",
    "vote_date": "2024-06-01",
    "is_passed": true
  },
  {
    "id": 5,
    "bill_tag": "L 125",
    "title": "Forslag til lov om ændring af arbejdsmiljøloven",
    "question": "Skal der indføres ret til at afbryde forbindelsen efter arbejdstid?",
    "description": "Dette lovforslag giver medarbejdere juridisk ret til ikke at skulle besvare arbejdsrelaterede henvendelser uden for normal arbejdstid, med visse undtagelser.",
    "for_description": "Retten til at koble fra er afgørende for mental sundhed og work-life balance. Stress og udbrændthed stiger, og medarbejdere har brug for klare grænser.",
    "against_description": "Loven vil hæmme virksomhedernes fleksibilitet, skade konkurrenceevnen og passe dårligt til moderne, dynamiske arbejdspladser med internationale samarbejdspartnere.",
    "url": "https://www.ft.dk/forslag/L125",
    "vote_date": "2024-09-18",
    "is_passed": false
  },
  {
    "id": 6,
    "bill_tag": "L 138",
    "title": "Forslag til lov om ændring af dyrevelfærdsloven",
    "question": "Skal der indføres forbud mod pelsdyravl i Danmark?",
    "description": "Lovforslaget forbyder opdræt af mink og andre pelsdyr til pelsproduktion med en udfasningsperiode på to år og kompensation til berørte erhvervsdrivende.",
    "for_description": "Pelsdyravl er etisk forkasteligt, dyrevelfærden er ofte mangelfuld, og branchen udgør også en potentiel sundhedsrisiko som set under COVID-19 pandemien.",
    "against_description": "Forbuddet vil ødelægge en traditionel dansk erhvervsgren, koste tusindvis af arbejdspladser i landdistrikter og sætte en farlig præcedens for statsindgreb.",
    "url": "https://www.ft.dk/forslag/L138",
    "vote_date": "2024-11-30",
    "is_passed": true
  },
  {
    "id": 7,
    "bill_tag": "L 156",
    "title": "Forslag til lov om ændring af planloven",
    "question": "Skal der lettes på reglerne for byggeri i landzone?",
    "description": "Forslaget letter byggemulighederne i landzone for at fremme bosætning og erhvervsudvikling i yderområder med simplificerede godkendelsesprocedurer.",
    "for_description": "Landdistrikterne affolkes, og vi har brug for flere boliger og arbejdspladser udenfor byerne. Mindre bureaukrati vil skabe vækst og livskraft.",
    "against_description": "Lempelser vil true naturområder, øge urban sprawl, belaste infrastrukturen og undergrave den planmæssige sammenhæng, som beskytter det åbne land.",
    "url": "https://www.ft.dk/forslag/L156",
    "vote_date": "2025-01-20",
    "is_passed": false
  },
  {
    "id": 8,
    "bill_tag": "L 171",
    "title": "Forslag til lov om ændring af energiloven",
    "question": "Skal Danmark have flere havvindmølleparker?",
    "description": "Lovforslaget giver grønt lys til etablering af tre nye store havvindmølleparker med en samlet kapacitet på 6 GW inden 2032.",
    "for_description": "Havvind er Danmarks grønne fremtid og nøglen til energiuafhængighed. Investeringen vil skabe jobs, eksportindtægter og sikre ren energi til fremtiden.",
    "against_description": "Projektet er ekstrem dyrt for skatteyderne, truer fiskeriet og havmiljøet, og energien kunne produceres billigere og mere pålideligt på andre måder.",
    "url": "https://www.ft.dk/forslag/L171",
    "vote_date": "2025-02-05",
    "is_passed": true
  },
  {
    "id": 9,
    "bill_tag": "L 184",
    "title": "Forslag til lov om ændring af lov om social service",
    "question": "Skal der indføres ret til kommunal hjemmehjælp for alle over 75 år?",
    "description": "Dette lovforslag sikrer, at alle borgere over 75 år får ret til minimum 2 timers ugentlig hjemmehjælp uanset økonomi og funktionsniveau.",
    "for_description": "Ældre skal have værdig behandling og støtte til at blive i eget hjem. Universel hjemmehjælp forebygger ensomhed, fald og indlæggelser.",
    "against_description": "Forslaget er ukritisk velfærdspopulisme, der vil koste kommunerne dyrt og tage ressourcer fra dem, der virkelig har brug for hjælpen.",
    "url": "https://www.ft.dk/forslag/L184",
    "vote_date": "2025-03-12",
    "is_passed": false
  },
  {
    "id": 10,
    "bill_tag": "L 199",
    "title": "Forslag til lov om ændring af restaurationsloven",
    "question": "Skal der indføres forbud mod engangsplastik i restaurationsbranchen?",
    "description": "Lovforslaget forbyder restauranter, cafeer og takeaway-steder at bruge engangsemballage af plastik fra 2026 med krav om genanvendelige eller komposterbare alternativer.",
    "for_description": "Plastikforurening er en global krise. Forbuddet vil reducere affald markant, fremme cirkulær økonomi og placere Danmark som grøn frontløber.",
    "against_description": "Alternative materialer er dyrere og ikke nødvendigvis mere miljøvenlige. Små restauranter vil blive hårdt ramt økonomisk, og forbrugerne vil betale prisen.",
    "url": "https://www.ft.dk/forslag/L199",
    "vote_date": "2025-04-08",
    "is_passed": true
  }
]