// <auto-generated />
using System;
using Hvadskaljegstemme.Data;
using Hvadskaljegstemme.Models.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hvadskaljegstemme.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226141940_AddBillTypeAndBillVoteDate")]
    partial class AddBillTypeAndBillVoteDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "bill_type", new[] { "beslutningsforslag", "lovforslag", "borgerforslag" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vote", new[] { "for", "against", "neither", "skip" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hvadskaljegstemme.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgainstExplanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("against_explanation");

                    b.Property<string>("BillTag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bill_tag");

                    b.Property<BillType>("BillType")
                        .HasColumnType("bill_type")
                        .HasColumnName("bill_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ForExplanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("for_explanation");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_passed");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<DateOnly>("VotedAt")
                        .HasColumnType("date")
                        .HasColumnName("voted_at");

                    b.HasKey("Id")
                        .HasName("pk_bills");

                    b.ToTable("bills", (string)null);
                });

            modelBuilder.Entity("Hvadskaljegstemme.Models.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<char>("Letter")
                        .HasColumnType("character(1)")
                        .HasColumnName("letter");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_parties");

                    b.ToTable("parties", (string)null);
                });

            modelBuilder.Entity("Hvadskaljegstemme.Models.PartyVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillId")
                        .HasColumnType("integer")
                        .HasColumnName("bill_id");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<Vote>("Vote")
                        .HasColumnType("vote")
                        .HasColumnName("vote");

                    b.HasKey("Id")
                        .HasName("pk_party_votes");

                    b.HasIndex("BillId")
                        .HasDatabaseName("ix_party_votes_bill_id");

                    b.HasIndex("PartyId")
                        .HasDatabaseName("ix_party_votes_party_id");

                    b.ToTable("party_votes", (string)null);
                });

            modelBuilder.Entity("Hvadskaljegstemme.Models.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("BillId")
                        .HasColumnType("integer")
                        .HasColumnName("bill_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Vote>("Vote")
                        .HasColumnType("vote")
                        .HasColumnName("vote");

                    b.HasKey("Id")
                        .HasName("pk_user_answers");

                    b.HasIndex("BillId")
                        .HasDatabaseName("ix_user_answers_bill_id");

                    b.ToTable("user_answers", (string)null);
                });

            modelBuilder.Entity("Hvadskaljegstemme.Models.PartyVote", b =>
                {
                    b.HasOne("Hvadskaljegstemme.Models.Bill", "Bill")
                        .WithMany("PartyVotes")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_party_votes_bills_bill_id");

                    b.HasOne("Hvadskaljegstemme.Models.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_party_votes_parties_party_id");

                    b.Navigation("Bill");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Hvadskaljegstemme.Models.UserAnswer", b =>
                {
                    b.HasOne("Hvadskaljegstemme.Models.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_answers_bills_bill_id");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Hvadskaljegstemme.Models.Bill", b =>
                {
                    b.Navigation("PartyVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
